sources = [
	'basecode/consts.cpp',
	'basecode/Element.cpp',
	'basecode/Qinfo.cpp',
	'basecode/DataHandler.cpp',
	'basecode/ZeroDimHandler.cpp',
	'basecode/ZeroDimParallelHandler.cpp',
	'basecode/BlockHandler.cpp',
	'basecode/OneDimHandler.cpp',
	'basecode/TwoDimHandler.cpp',
	'basecode/AnyDimHandler.cpp',
	'basecode/DataHandlerWrapper.cpp',
	'basecode/FieldDataHandlerBase.cpp',
	'basecode/MsgDataHandler.cpp',
	'basecode/ZombieHandler.cpp',
	'basecode/Eref.cpp',
	'basecode/Finfo.cpp',
	'basecode/DestFinfo.cpp',
	'basecode/Cinfo.cpp',
	'basecode/SrcFinfo.cpp',
	'basecode/ValueFinfo.cpp',
	'basecode/SharedFinfo.cpp',
	'basecode/FieldElementFinfo.cpp',
	'basecode/Id.cpp',
	'basecode/ObjId.cpp',
	'basecode/DataId.cpp',
	'basecode/SetGet.cpp',
	'basecode/OpFunc.cpp',
	'basecode/FieldOpFunc.cpp',
	'basecode/SparseMatrix.cpp',
	'basecode/PrepackedBuffer.cpp',
	'basecode/FuncBarrier.cpp',
	'basecode/doubleEq.cpp',
	'basecode/ReduceBase.cpp',
	'basecode/main.cpp',
	'basecode/testAsync.cpp',
	
	'biophysics/SynBase.cpp',
	'biophysics/IntFire.cpp',
	'biophysics/IzhikevichNrn.cpp',
	'biophysics/LeakyIaF.cpp',
	'biophysics/Synapse.cpp',
	'biophysics/Compartment.cpp',
	'biophysics/SymCompartment.cpp',
	'biophysics/ChanBase.cpp',
	'biophysics/SynChanBase.cpp',
	'biophysics/HHChannel.cpp',
	'biophysics/HHGate.cpp',
	'biophysics/SynChan.cpp',
	'biophysics/SpikeGen.cpp',
	'biophysics/CaConc.cpp',
	'biophysics/Nernst.cpp',
	'biophysics/GHK.cpp',
	'biophysics/NMDAChan.cpp',
	'biophysics/HHGate2D.cpp',
	'biophysics/HHChannel2D.cpp',
	'biophysics/MgBlock.cpp',
	'biophysics/VectorTable.cpp',
	'biophysics/MarkovRateTable.cpp',
	'biophysics/MarkovChannel.cpp',
	'biophysics/MarkovGslSolver.cpp',
	'biophysics/MatrixOps.cpp',
	'biophysics/MarkovSolverBase.cpp',
	'biophysics/MarkovSolver.cpp',
	'biophysics/ReadCell.cpp',
	'biophysics/testBiophysics.cpp',
	
	'builtins/Arith.cpp',
	'builtins/Group.cpp',
	'builtins/Mdouble.cpp',
	'builtins/Mstring.cpp',
	'builtins/TableBase.cpp',
	'builtins/TableEntry.cpp',
	'builtins/Table.cpp',
	'builtins/StimulusTable.cpp',
	'builtins/Stats.cpp',
	'builtins/Interpol2D.cpp',
	'builtins/HDF5WriterBase.cpp',
	'builtins/HDF5DataWriter.cpp',
	'builtins/testBuiltins.cpp',
	
	'device/PulseGen.cpp',
	'device/DiffAmp.cpp',
	'device/PIDController.cpp',
	'device/RC.cpp',
	
	'geom/Geometry.cpp',
	'geom/Surface.cpp',
	'geom/Panel.cpp',
	'geom/CylPanel.cpp',
	'geom/SpherePanel.cpp',
	'geom/HemispherePanel.cpp',
	'geom/DiskPanel.cpp',
	'geom/RectPanel.cpp',
	'geom/TriPanel.cpp',
	'geom/testGeom.cpp',
	
	'hsolve/HSolveStruct.cpp',
	'hsolve/HinesMatrix.cpp',
	'hsolve/HSolvePassive.cpp',
	'hsolve/RateLookup.cpp',
	'hsolve/HSolveActive.cpp',
	'hsolve/HSolveActiveSetup.cpp',
	'hsolve/HSolveInterface.cpp',
	'hsolve/HSolve.cpp',
	'hsolve/HSolveUtils.cpp',
	'hsolve/testHSolve.cpp',
	'hsolve/ZombieCompartment.cpp',
	'hsolve/ZombieCaConc.cpp',
	'hsolve/ZombieHHChannel.cpp',
	
	'kinetics/PoolBase.cpp',
	'kinetics/Pool.cpp',
	'kinetics/BufPool.cpp',
	'kinetics/FuncPool.cpp',
	'kinetics/Reac.cpp',
	'kinetics/Enz.cpp',
	'kinetics/MMenz.cpp',
	'kinetics/Species.cpp',
	'kinetics/ReadKkit.cpp',
	'kinetics/ReadCspace.cpp',
	'kinetics/MathFunc.cpp',
	'kinetics/SumFunc.cpp',
	'kinetics/lookupSizeFromMesh.cpp',
	'kinetics/testKinetics.cpp',
	
	'ksolve/Port.cpp',
	'ksolve/Stoich.cpp',
	'ksolve/KinSparseMatrix.cpp',
	'ksolve/ZombiePool.cpp',
	'ksolve/ZombieBufPool.cpp',
	'ksolve/ZombieFuncPool.cpp',
	'ksolve/ZombieReac.cpp',
	'ksolve/ZombieEnz.cpp',
	'ksolve/ZombieMMenz.cpp',
	'ksolve/ZombieSumFunc.cpp',
	'ksolve/RateTerm.cpp',
	'ksolve/FuncTerm.cpp',
	'ksolve/GssaStoich.cpp',
	'ksolve/testKsolve.cpp',
	
	'manager/SimManager.cpp',
	'manager/testSimManager.cpp',
	
	'mesh/ChemMesh.cpp',
	'mesh/MeshEntry.cpp',
	'mesh/CylMesh.cpp',
	'mesh/CubeMesh.cpp',
	'mesh/Boundary.cpp',
	'mesh/Stencil.cpp',
	'mesh/testMesh.cpp',
	
	'msg/Msg.cpp',
	'msg/DiagonalMsg.cpp',
	'msg/OneToAllMsg.cpp',
	'msg/OneToOneMsg.cpp',
	'msg/SingleMsg.cpp',
	'msg/SparseMsg.cpp',
	'msg/ReduceMsg.cpp',
	'msg/testMsg.cpp',
	
	'pymoose/moosemodule.cpp',
	
	'randnum/mt19937ar.cpp',
	
	'regressionTests/regressionTest.cpp',
	'regressionTests/rtTable.cpp',
	'regressionTests/rtReadKkit.cpp',
	'regressionTests/rtHHnetwork.cpp',
	'regressionTests/rtReacDiff.cpp',
	'regressionTests/perfTestMarkovSolver.cpp',
	'regressionTests/benchmarkTests.cpp',
	
	'scheduling/Clock.cpp',
	'scheduling/Tick.cpp',
	'scheduling/TickMgr.cpp',
	'scheduling/testScheduling.cpp',
	
	'shell/Shell.cpp',
	'shell/ShellCopy.cpp',
	'shell/ShellSetGet.cpp',
	'shell/ShellThreads.cpp',
	'shell/ProcessLoop.cpp',
	'shell/LoadModels.cpp',
	'shell/Neutral.cpp',
	'shell/Wildcard.cpp',
	'shell/testShell.cpp',
	
	#~ 'smol/SmolSim.cpp',
	#~ 'smol/SmolPool.cpp',
	#~ 'smol/SmolMol.cpp',
	#~ 'smol/SmolReac.cpp',
	#~ 'smol/SmolEnz.cpp',
	#~ 'smol/SmolMMenz.cpp',
	#~ 'smol/testSmol.cpp',
	
	'utility/strutil.cpp',
	'utility/types.cpp',
	'utility/setupenv.cpp',
	'utility/numutil.cpp',
	'utility/Annotator.cpp',
]
