# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt update && apt -y install cmake git libgsl-dev
    - apt -y install python3-numpy python3-matplotlib python3-pip python3-dev
    - apt -y install python-numpy python-matplotlib python-pip python-dev
  script:
    - python3 -m pip install setuptools pip --user --upgrade
    - python3 -m pip install python-libsbml --user --upgrade
    - python3 -m pip install pyneuroml --user --upgrade
    - python3 -m pip install sympy scipy --user --upgrade
    - python3 setup.py build test 
    - python3 setup.py install --user
    - python3 -c "import moose; moose.test()"
