- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v0.6.1
  hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-case-conflict 
      - id: check-docstring-first
      - id: debug-statements

