#!/bin/bash

# This script updates the repository and its subrepositories, recursively.

git submodule update --init
git submodule foreach '[ "$path" = "moogli" ] && branch=geometry || branch=master; git pull origin $branch; git checkout $branch' 
