language: cpp
branches:
    only:
        - master
        - devel

compiler:
    - clang
    - gcc

matrix:
    # works on Precise and Trusty
    - os: linux
      addons:
          apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - g++-5
              env:
                  - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

script: 
    - cmake . && make && ctest --output-on-failure

