INVALID 				= 6

INTERIOR 				= 7
BOUNDARY 				= 8

SAME_OBJECT 			= 9
OTHER_OBJECT 			= 10
NO_OBJECT 				= 11

RUBBERBAND_SELECTION 	= 12
VALID 					= 13

ITEM 					= 0
CONNECTOR				= 1
CONNECTION				= 2
EMPTY					= 3

COMPARTMENT 			= 14
COMPARTMENT_BOUNDARY 	= 4
COMPARTMENT_INTERIOR   	= 5

GROUP					= 15
GROUP_BOUNDARY 			= 16
GROUP_INTERIOR   		= 17
