#!/bin/sh 

echo "###############################################################"
echo "# Generating C++ Documentation                                #"
echo "###############################################################"
doxygen ./Doxyfile.full 

echo "##############################################################"
echo "# Generating Python Documentation                            #"
echo "##############################################################"

( cd Docs/user/py && make html || true )

