ELECTRICAL_SIMULATION_DT_CLOCKS         = [1,2,3,4,5,6,7]
ELECTRICAL_PLOT_UPDATE_INTERVAL_CLOCKS  = [8]
ELECTRICAL_DIFFUSION_INTERVAL_CLOCKS    = [10]

CHEMICAL_SIMULATION_DT_CLOCKS           = [11, 12, 13, 14, 15, 16, 17]
CHEMICAL_PLOT_UPDATE_INTERVAL_CLOCKS    = [18]
CHEMICAL_DIFFUSION_DT_CLOCKS            = [10]
