#!/bin/sh

# AUTHOR    : AVIRAL GOEL
# EMAIL-ID  : aviralg@ncbs.res.in
# UPDATED BY: Harsha Rani
# UPDATED ON: Aug 16 2016
echo "Installing moose-core dependencies"
sudo -E apt-get install g++ libgsl0-dev libhdf5-dev libpython-dev python-numpy 


#echo "Installing moose-gui and moogli dependencies"
sudo -E apt-get install python-setuptools libqt4-dev python-qt4-dev libopenscenegraph-dev python-qt4-gl python-sip-dev python-matplotlib python-scipy python-suds python-networkx python-pygraphviz
