#!/bin/bash

echo "###############################################################"
echo "# Generating C++ Documentation                                #"
echo "###############################################################"
#Files will be created in cpp/html with in `doxygen` folder
( 
    cd doxygen
    doxygen Doxyfile
)

echo "##############################################################"
echo "# Generating Python Documentation                            #"
echo "##############################################################"
#Files will be created in _build/html 
mkdir -p _build
sphinx-build . _build

