name: moose 
version: '3.1+git'
summary: Neuronal modeling software spanning molecules, electrophysiology and networks
description: |
    MOOSE is the Multiscale Object-Oriented Simulation Environment. It is designed
    to simulate neural systems ranging from biochemical signaling to complex models
    of single neurons, circuits, and large networks. A typical use case is to model
    neural activity-driven synaptic plasticity, in which network activity to
    synapses triggers biochemical reaction-diffusion events, which in turn modulate
    ion channels to give rise to synaptic plasticity.

grade: devel
confinement: devmode 

apps:
    moose :
        command : moose 

parts:
  desktop:
      plugin: cmake
      configflags: [ "-DCMAKE_INSTALL_PREFIX=/usr" ]
      source : . # https://github.com/BhallaLab/moose.git
      build-packages:
          - cmake
          - g++
          - libgsl-dev
          - libhdf5-serial-dev
          - python-dev
          - python-numpy

      stage-packages:
          - libgsl2
          - libhdf5-10
          - python-networkx
          - python-matplotlib 
          - python-numpy
          - python-qt4
          - python
