name: moose # you probably want to 'snapcraft register <name>'
version: '3.1.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Neuronal modeling software spanning molecules, electrophysiology and networks
description: |
    MOOSE is the Multiscale Object-Oriented Simulation Environment. It is designed
    to simulate neural systems ranging from biochemical signaling to complex models
    of single neurons, circuits, and large networks. A typical use case is to model
    neural activity-driven synaptic plasticity, in which network activity to
    synapses triggers biochemical reaction-diffusion events, which in turn modulate
    ion channels to give rise to synaptic plasticity.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    moose :
        command : moose 


parts:
  desktop:
      plugin: cmake
      configflags: [ "-DCMAKE_INSTALL_PREFIX=/usr", "-DMOOSE_VERSION=3.1.2" ]
      source : .
      build-packages:
          - cmake
          - g++
          - libgsl-dev
          - libhdf5-serial-dev
      stage-packages:
          - libgsl2
          - libhdf5-10
